baseURL: https://shiroyuki.dev
title: charlola.mode
paginate: 5
theme: charlolamode

menu:
    main:
        - name: Portfolio
          url: /portfolio/
          weight: 2
        - name: Blog
          url: https://blog.shiroyuki.dev
          weight: 3
        - name: Komisi
          url: https://comission.shiroyuki.dev
          weight: 4
        - name: Kontak
          url: /kontak/
          weight: 5

params:
    hideFooter: true
    author: Aghits Nidallah
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Aghits Nidallah
        description: |
          Halo, nama saya Aghits Nidallah 👋.

          Saya seorang pengembang web, mahasiswa, dan manusia yang hidup
          dengan menikmati secangkir kopi 24/7 ☕️.
        imageUrl: "/images/profile.png"
        imageTitle: Foto saya
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: facebook
          url: https://www.facebook.com/irlnidallah/
        - name: twitter
          url: https://twitter.com/irlnidallah
        - name: instagram
          url: https://instagram.com/irlnidallah
        - name: youtube
          url: https://www.youtube.com/@aghitsnidallah7953/
        - name: github
          url: "https://github.com/NikarashiHatsu"
        - name: linkedin
          url: "https://www.linkedin.com/in/aghits-nidallah-9b6728221/"

    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
